resources:
- name: repo
  type: git
  source:
    uri: https://github.com/bdfoster/nomatic-events.git
 
jobs:
- name: test
  public: true
  serial: true
  plan:
  - get: repo
    trigger: true
  - task: cache-repo
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: bdfoster/node
          tag: latest
      inputs:
      - name: repo
      outputs:
      - name: cache
      run:
        path: sh
        args:
        - -exc
        - |
          cp -R repo/* cache

  - task: npm install
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: bdfoster/node
          tag: latest
      inputs:
      - name: repo
      outputs:
      - name: npm-install-cache
      run:
        path: sh
        args:
          - -exc
          - |
            cp -R repo/* npm-install-cache
            cd npm-install-cache
            npm install

  - task: npm run compile
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: bdfoster/node
          tag: latest
      inputs:
      - name: npm-install-cache
        path: '.'
      run:
        path: sh
        args:
          - -exc
          - |
            npm run compile

  - task: npm test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: bdfoster/node
          tag: latest
      inputs:
      - name: npm-install-cache
        path: '.'
      run:
        path: sh
        args:
          - -exc
          - |
            npm test
