resources:
- name: repo
  type: git
  source:
    uri: https://github.com/bdfoster/nomatic-events.git
 
jobs:
- name: run-tests
  plan:
  - get: repo
    trigger: true
  - task: test
    config:
      image_resource:
        type: docker-image
        source:
          repository: bdfoster/node
          tag: 'latest'
      inputs:
      - name: repo
      run:
        path: sh
        args:
          - -exc
          - |
            cd repo
            npm install
            npm test
