resources:
- name: repo
  type: git
  source:
    uri: https://github.com/bdfoster/nomatic-events.git
 
jobs:
- name: test
  public: true
  serial: true
  plan:
  - get: repo
    trigger: true
  - task: npm install
    config:
      image_resource:
        type: docker-image
        source:
          respository: bdfoster/node
          tag: 'latest'
      inputs:
      - name: repo
      outputs:
      - name: repo
      run:
        path: sh
        - -exc
        - |
          cd repo
          npm install
  - task: npm test
    config:
      image_resource:
        type: docker-image
        source:
          repository: bdfoster/node
          tag: 'latest'
      inputs:
      - name: repo
      run:
        path: sh
        args:
          - -exc
          - |
            cd repo
            npm test
